#!/usr/bin/env bash
# Modifie le fichier /etc/hosts pour que localhost pointe vers 127.0.0.2 et facebook.com vers 8.8.8.8

# Sauvegarde de /etc/hosts
cp /etc/hosts /etc/hosts.bak

# Supprime les lignes existantes pour localhost et facebook.com
sed -i '/localhost/d' /etc/hosts
sed -i '/facebook.com/d' /etc/hosts

# Ajoute les nouvelles entrées
echo "127.0.0.2 localhost" >> /etc/hosts
echo "8.8.8.8 facebook.com" >> /etc/hosts
